### ISSUE TITLE
Syntax errors in /etc/bgpd.conf?

### ISSUE THREAD

**Issue by robert-scheck** [openbgpd-portable/openbgpd-portable#11]
Since the latest commits I'm ending up with this when starting `bgpd` with an unmodified configuration:

```
Mai 07 00:54:49 centos8 bgpd[19877]: pushfile: /var/db/rpki-client/openbgpd: No such file or directory
Mai 07 00:54:49 centos8 bgpd[19877]: /etc/bgpd.conf:17: failed to include file /var/db/rpki-client/openbgpd
Mai 07 00:54:49 centos8 bgpd[19877]: /etc/bgpd.conf:104: syntax error
Mai 07 00:54:49 centos8 bgpd[19877]: /etc/bgpd.conf:105: syntax error
Mai 07 00:54:49 centos8 bgpd[19877]: /etc/bgpd.conf:114: syntax error
Mai 07 00:54:49 centos8 bgpd[19877]: config file /etc/bgpd.conf has errors
```

The first two errors are clear, there is no `rpki-client` by default. But what about the syntax errors? Line 104, 105 and 114 are:

```
match from ebgp set { community delete $ASN:* }
match from ebgp set { large-community delete $ASN:*:* }
match from any community GRACEFUL_SHUTDOWN set { localpref 0 }
```

Did I make any mistake here when grabbing latest OpenBGPD from Git? I cloned the portable repository just a few minutes ago and run `./autogen.sh; ./configure; make -k; make distcheck` and used that tarball for the CentOS 8 build.

**Comment by cjeker** [comment]
This is a bug in bison. If you build with YACC=byacc ./configure then the syntax errors are gone. It is unclear to me how bison fails here. There is an incompatibility between bison and yacc.

**Comment by cjeker** [comment]
I should probably change the configure test to only check for byacc and yacc so that others don't fall into this trap.

**Comment by robert-scheck** [comment]
Oh, this reminds me that the absence of `byacc` (and `yacc`) does not lead to any fault in `./configure` but then in make. Not sure if this behaviour is desired.

**Comment by cjeker** [comment]
Check out 78c3cddb3838c62a939796e8f2352fd8100a41ad
This should properly detect yacc and byacc and cause configure to fail if non is available.

**Comment by cjeker** [comment]
Great, bison adds a yacc wrapper on linux and so we're kind of back to square 1.
Grmbl grmbl #$*!

**Comment by cjeker** [comment]
In the meantime I actually figured out the issue. The grammer used `"{"` in places where `'{'` is wanted. Added a local patch to solve this.
