### ISSUE TITLE
permission denied on show fib and fib-update not working

### ISSUE THREAD

**Issue by mikegeoffrey** [openbgpd-portable/openbgpd-portable#15]
I saw a pdf from Claudio from a couple of years ago about portable version, saying something like fib-update is not in the portable version, is that the correct understanding?

I'm on centos7 3.10.0-1127.8.2.el7.x86_64 using openbgpd-6.7p0, I exchange my routes fine with my neighbors, and see the neighbors route updates in rib, but the fib is never updated with those routes.  When I do bgctl show fib I get permission denied, regardless of what user I run bgpd as.

my next hops are all marked as valid.

I'm scratching my head, anyhelp out there?

**Comment by cjeker** [comment]
Yes, currently the FIB is not supported for Linux systems. The necessary netlink code has not yet been written.
This is why bgpctl show fib returns an error. Should probably adjust the error reported until there is support.

**Comment by robert-scheck** [comment]
@mikegeoffrey, in case my openbgpd-6.7p0-2.el7.x86_64 RPM package from EPEL 7 was used on CentOS 7…it even already says so (`rpm -qi openbgpd`):

```
[…]
Description :
OpenBGPD is a free implementation of the Border Gateway Protocol (BGP),
Version 4. It allows ordinary machines to be used as routers exchanging
routes with other systems speaking the BGP protocol.

This is the portable version and it does not have the means to influence
kernel routing tables. It is only suitable for route servers/collectors.
```

In case this needs to be clarified as well, please let me know.

**Comment by cjeker** [comment]
Just as an update, with the latest version the linux FIB support is enabled by default.
It may still have some rough edges but should be usable.

**Comment by robert-scheck** [comment]
Given the reference of CentOS 7 in the initial description, I kindly would like to point out that libmnl(-devel) shipped by default in CentOS 7 is too old however. EPEL 8 and 9 provide RPM packages with Linux FIB support enabled, if it helps somehow.

**Comment by cjeker** [comment]
As mentioned more than 2 weeks ago this should be fixed. Please open an new issue if there are still problems.
