### ISSUE TITLE
RTR protocol: Invalid argument and RTR session not coming up

### ISSUE THREAD

**Issue by pierky** [openbgpd-portable/openbgpd-portable#23]
Hello,

while testing the RTR support in 6.9p0, I've observed the daemon not being able to establish the connection with the local validator.

This is the log, where you can see the `Invalid argument` error during the RTR session setup:

```
startup
PF_KEY not available, disabling ipsec
session engine ready
rtr engine ready
route decision engine ready
rtr MyValidator1: connect to 192.0.2.10:3323: Invalid argument
listening on (unknown)
listening on (unknown)
SE reconfigured
neighbor 192.0.2.22: state change None -> Idle, reason: None
neighbor 2001:db8:1:1::22: state change None -> Idle, reason: None
neighbor 192.0.2.111: state change None -> Idle, reason: None
neighbor 192.0.2.11: state change None -> Idle, reason: None
neighbor 192.0.2.22: state change Idle -> Active, reason: Start
neighbor 2001:db8:1:1::22: state change Idle -> Active, reason: Start
neighbor 192.0.2.111: state change Idle -> Active, reason: Start
neighbor 192.0.2.11: state change Idle -> Active, reason: Start
RTR engine reconfigured
RDE reconfigured
running softreconfig in
softreconfig in done
RDE soft reconfiguration done
neighbor 192.0.2.111: state change Active -> OpenSent, reason: Connection opened
neighbor 192.0.2.111: state change OpenSent -> OpenConfirm, reason: OPEN message received
neighbor 192.0.2.111: state change OpenConfirm -> Established, reason: KEEPALIVE message received
neighbor 192.0.2.111: sending IPv4 unicast EOR marker
Rib Loc-RIB: neighbor 192.0.2.111 AS1: update 193.0.0.0/24 via 192.0.2.111
neighbor 192.0.2.111: received IPv4 unicast EOR marker
```

The 6.9p0 is executed within a Docker container: also the validator runs inside another Docker container, sharing the same *network*.

The same configuration works fine on an OpenBSD instance connected directly to the same Docker *network* above (same validator, same *network*, just using a bridge between the VM and Docker - see [ARouteServer's integration testing for OpenBGPD on OpenBSD](https://arouteserver.readthedocs.io/en/latest/LIVETESTS.html#openbgpd-live-tests-environment))

Since using the same config I'm having this issue only on the portable edition, it seems to me (but of course I may be wrong) that it could be something related to the porting to Linux.

**Comment by cjeker** [comment]
Can you give this diff a try? I think the issue is that on linux the code is differently optimized and the len passed to connect is put into the argument register before addr2sa() changed it. At least this is my feeling what is going on here.

[bdiff.txt](https://github.com/openbgpd-portable/openbgpd-portable/files/6411630/bdiff.txt)

**Comment by pierky** [comment]
Thanks @cjeker for looking into it.

Same error.

I've applied the patch in the following way, is it correct?

```
cd /root/openbgpd-portable-6.9p0 && \
    ./autogen.sh && \
    YACC=byacc ./configure --sysconfdir=/etc/bgpd && \
    curl -L https://github.com/openbgpd-portable/openbgpd-portable/files/6411630/bdiff.txt -o issue23-rtr.patch && \
    patch ./openbsd/src/usr.sbin/bgpd/bgpd.c < issue23-rtr.patch && \
    make && \
    make install
```

FWIW, an `strace` says the following:
```
connect(6, {sa_family=AF_INET, sin_port=htons(3323), sin_addr=inet_addr("192.0.2.10")}, 32767) = -1 EINVAL (Invalid argument)
```

If I also configure `local-address 192.0.2.2`, I receive a similar error: 

```
rtr MyValidator1: bind to 192.0.2.2: Invalid argument
```

**Comment by cjeker** [comment]
Looking at the 3rd argument of connect this looks indeed like a not initialized variable. The patch should solve this. Need to look into this why it does not do that for you.

PS: You no longer need byacc, bison works just fine.

**Comment by cjeker** [comment]
I checked on my debian 10 system and my fix seems to fix this issue.

**Comment by pierky** [comment]
Oh right, I see, I was patching the wrong file, the one inside `openbsd/src/usr.sbin/bgpd/` instead of `src/bgpd/bgpd.c`.

With the snippet below, the patch works fine, thanks a lot.

Are you planning to release a p1 to include this fix?

```
cd /root/openbgpd-portable-6.9p0 && \
    ./autogen.sh && \
    ./configure --sysconfdir=/etc/bgpd && \
    curl -L https://github.com/openbgpd-portable/openbgpd-portable/files/6411630/bdiff.txt -o issue23-rtr.patch && \
    patch ./src/bgpd/bgpd.c < issue23-rtr.patch && \
    make && \
    make install
```

**Comment by cjeker** [comment]
Yes, but I want to look at your other issue first. Two bugs one release :)
