### ISSUE TITLE
session state transition with "depend on" directly to down rather than graceful restart on link loss

### ISSUE THREAD

**Issue by rscheff** [openbgpd-portable/openbgpd-portable#24]
While looking at improving the transition speed of bgpd on a link-down event, we found that even when using the "depend on" keyword for a peer relationship, the session would be retried using graceful restart. Only after the timeout of the graceful restart,
the session would transition to down.

It appears that this is unnecessarily delaying the session state transition - while the interface, upon which the seesion depends is
down, it is counter-intuitive to be trying to gracefully restart the session all over again, and not transitioning the state directly to down.

In our case, as we trigger subsequent actions based on the FSM transitions, this unnecessarily delayed these actions by 30 seconds.

The current behavior (graceful restart after session loss) can be retained for normal peering configurations without the "depend on" keyword - as alternate routes may be available to re-establish the session. However, when it is known to the admin, that no alternate routes will be available, doing a faster transition to session down, and skipping the graceful restart, appears to be useful (lower overhead, faster state transition).

**Comment by cjeker** [comment]
Did you try to use 'announce restart no' together with 'depend on'?
Does that fix your issue?

**Comment by rscheff** [comment]
No, we did not try this. I just to make it clear, that we are not looking at the BGP protocol state transition, but the state transition within bgpd (where custom code will trigger a message to a different piece in our framework, to do things). Originally we did this for major session state transitions (e.g. session_down). We had to change it to trigger now for each iteration of a graceful_restart, triggering more overhead (additional checks if the routes are still present etc). Will "announce restart no" stop performing graceful restarts and transition directly to down (internally)?

**Comment by cjeker** [comment]
The 30 seconds are because of graceful restart. If peers agree to use graceful restart then routes will be retained when the TCP connection is closed without NOTIFICATION. By using 'announce restart no' the feature should be disabled and then a connection drop would result in an immediate flush of the RIB.

**Comment by rscheff** [comment]
We are using (exposing) some internal bgpd state - not actually using the RIB/FIB directly. I asked my colleagues to check if the combination will make the internal state-machine transitions without the graceful-restart.

**Comment by cjeker** [comment]
The session engine should issue a IMSG_SESSION_DOWN if GR is disabled.
Also if the other side did not announce GR restart then an IMSG_SESSION_DOWN is issued.
In both cases the RDE should flush the RIB immediatly and not mark routes stale.

**Comment by cjeker** [comment]
There have been some changes to the capability negotiation and graceful restart capability handling. This has been released in 7.0.
You may need to add 'announce restart no' to your config to enforce that GR is off.
