### ISSUE TITLE
Question: how to construct a bgp client?

### ISSUE THREAD

**Issue by grandnew** [openbgpd-portable/openbgpd-portable#26]
Hi, all.
I'm new to this project. I followed the `INSTALL` rule to build the project and added user `_bgpd` so I can start the `bgpd` .
But I didn't find an example about how to construct a bgp client so as to communicate with `bgpd` ?
In order to do this, what should I do? Could you please give me an example? Thanks!

**Comment by cjeker** [comment]
Have a look at the installed example bgpd.conf file and also at the shipped manual pages for bgpd(8), bgpd.conf(5) and bgpctl(8). This should explain how to configure and run OpenBGPD.
Any BGP implementation can be used as a client, be it hardware routers or software like bird, exabgp. How to setup and run such clients is outside of the scope of OpenBGPD.
