### ISSUE TITLE
Docker container with OpenBGPD portable?

### ISSUE THREAD

**Issue by robert-scheck** [openbgpd-portable/openbgpd-portable#32]
When I started the rpki-client Docker container, I also played around with OpenBGPD in a container for testing purposes (but never finished it). During my Easter holidays I decided to get rid of the half finished bits on my disk, did the remaining work and published it. Now I wonder if you're interested in getting [openbgpd-container](https://github.com/robert-scheck/openbgpd-container) transferred into your openbgpd-portable GitHub organisation. I would continue the maintenance of course (fortunately most OpenBGPD changes are internally, but not relevant for packaging etc. which makes it quite easy for me to maintain it), like I do for rpki-client already.

**Comment by robert-scheck** [comment]
Thank you very much! Unfortunately I've most likely killed my granted owner permissions when just transferring my existing repository to the "openbgpd-portable" namespace (I chose to transfer rather to import to keep the stored secrets, workflow settinsg etc.), because I no longer can access the settings of the "openbgpd-container" repository. Other than that the transfer worked absolutely fine. May I kindly ask you to apply the permissions again? And again, thank you!

**Comment by cjeker** [comment]
No worries, thanks for all your work. I changed you role to admin for "openbgpd-container". Lets see if that was enough.

**Comment by robert-scheck** [comment]
Yes, now it looks like before! Thanks :)
