### ISSUE TITLE
ADD-PATH + `rde evaluate all`

### ISSUE THREAD

**Issue by pierky** [openbgpd-portable/openbgpd-portable#37]
Hello,

I see you added ADD-PATH support in 7.5, that's great!

While I was working to extend the test cases which I use in ARouteServer to test the integration of the functionality, I've noticed something that I'd like to share with you.

So, I understand from a bgpd error message that ADD-PATH send and `rde evaluate all` cannot coexist. This is kind of sad because it might lead to cases where the path-hiding mitigation offered by `rde evaluate all` can get lost if ADD-PATH send is enabled for a client but the client doesn't turn the "rx" capability on on its side.

The scenario I'm using to run these tests is the following one: https://github.com/pierky/arouteserver/tree/master/tests/live_tests/scenarios/path_hiding Here, AS3 has no ADD-PATH rx capability set on its side, so even though ADD-PATH send is configured on the route server side, it won't receive the second-best-path.

I understand that a similar situation may be a bit odd to be found in a real-life scenario, and I also understand that there may be implementation details and intricacies behind the two functionalities, at the same time I preferred to double check with you if you see any chance of enabling `rde evaluate all` support even for ADD-PATH enabled clients.

Thanks!

**Comment by cjeker** [comment]
Change was done upstream, should show up tomorrow in -portable.
