### ISSUE TITLE
Upload signing public key of OpenBGPD to keys.openpgp.org?

### ISSUE THREAD

**Issue by robert-scheck** [openbgpd-portable/openbgpd-portable#40]
Do you see any chance to upload the public key of RSA key BA3DA14FEE657A6D7931C08EC755429BA6A969A8, being used for signing OpenBGPD release tarballs, to keys.openpgp.org? This would allow Fedora to switch from the current binary GnuPG output blob (manually created) to the ASCII format provided there.

**Comment by cjeker** [comment]
Done. Please check if this works for your need.

**Comment by robert-scheck** [comment]
Thank you! Unfortunately keys.openpgp.org [strips all user IDs unless the owner of the corresponding email address has allowed them to be published](https://superuser.com/questions/1485213/gpg-cant-import-key-new-key-but-contains-no-user-id-skipped). So, this ends with `Can't check signature: Bad public key` right now. But I don't want to pressure you into this, thus it's up to you. I also can keep the binary GnuPG output blob further on.

**Comment by cjeker** [comment]
I just finished the email verification step. It just took a bit long to receive their mail.

**Comment by robert-scheck** [comment]
Ah. Now it works perfectly, thank you very much!
