### ISSUE TITLE
openbgpd-7.6/src/bgpd/kroute-linux.c:213: undefined reference to `mnl_socket_open2'

### ISSUE THREAD

**Issue by robert-scheck** [openbgpd-portable/openbgpd-portable#41]
Building the OpenBGPD 7.6 release on CentOS 7 with its libmnl 1.0.3 (when using `--enable-netlink`) fails like this :

```
bgpd-kroute-linux.o: In function `kr_init':
/builddir/build/BUILD/openbgpd-7.6/src/bgpd/kroute-linux.c:213: undefined reference to `mnl_socket_open2'
collect2: error: ld returned 1 exit status
make[1]: *** [bgpd] Error 1
```

Given [libmnl 1.0.3 is old](https://www.netfilter.org/projects/libmnl/downloads.html), I am _not_ expecting any backwards compatibility, but a proper error from `./configure` would make sense from my point of view. `mnl_socket_open2()` was introduced with [libmnl 1.0.4](https://www.netfilter.org/pub/libmnl/changes-libmnl-1.0.4.txt).

**Comment by cjeker** [comment]
Since this is still very experimental it should be possible to just not use mnl_socket_open2().
Requires to use fcntl() afterwards but that is fine. So if that helps with portability to older systems then I think
that may be the way to go.

**Comment by robert-scheck** [comment]
I'm not sure if it's worth the effort when looking to [Repology](https://repology.org/project/libmnl/badges), because only RHEL/CentOS 7 (reaching EOL at 2024-06-30) and its derivatives such as Amazon Linux 2, Rosa Server 7 or Scientific Linux 7 seem to be affected, when it comes to still active/maintained Linux distributions.

![image](https://repology.org/badge/vertical-allrepos/libmnl.svg)

**Comment by cjeker** [comment]
OK, since it only affect super old releases lets just bail in configure.
I merged your diff for that.
