### ISSUE TITLE
Support of pftable in Openbgpd7.6

### ISSUE THREAD

**Issue by janakktrivedi** [openbgpd-portable/openbgpd-portable#44]
Hi @cjeker 

It seems use of pftable(to store bgp prefixes) in bgpd has stopped supporting in newer portable release. Do you know if there is any plan to include this feature in upcoming releases ?
It is one of the coolest feature we have been using since more than 10 years(Thanks for that :) ) hence just wondering.

Thanks
Janak

**Comment by cjeker** [comment]
Please provide more information what is not working and where exactly. Is this a -portable build on OpenBSD?
I did try a config with `allow from any set pftable "bgpd"` on OpenBSD-current and it does work there.
In any case we did not stop to support the feature, this sounds more that some kind of bug sneaked into the release.

**Comment by janakktrivedi** [comment]
Hi @cjeker 
I am using OpenBGPD7.6 portable in FreeBSD 13.1 version where bgpd returns there is no support of pftable. Please find here more details:

Error:
`
# bgpd -n
pftable not supported
/usr/local/etc/bgpd.conf:39: Couldn't register table
pftable not supported
/usr/local/etc/bgpd.conf:40: Couldn't register table
`

Line 39 & 40 in /usr/local/etc/bgpd.conf:
`
allow quick from 10.240.103.177 set pftable bmview0
allow quick from 10.240.103.178 set pftable bmview1
`

FreeBSD Version:
`
# uname -a
FreeBSD fpf1.swe6 13.1-RELEASE-p2 FreeBSD 13.1-RELEASE-p2 GENERIC amd64
`

OpenBGPD version:
`# pkg info openbgpd7
openbgpd7-7.6
Name           : openbgpd7
Version        : 7.6
Installed on   : Sat Oct 29 10:34:07 2022 UTC
Origin         : net/openbgpd7
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : net
Licenses       : MIT
Maintainer     : pi@FreeBSD.org
WWW            : https://www.openbgpd.org/
Comment        : Free implementation of the Border Gateway Protocol, Version 4
Options        :
        IPV6LLPEER     : on
Shared Libs required:
        libevent-2.1.so.7
Annotations    :
        FreeBSD_version: 1301000
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 579KiB
Description    :
OpenBGPD is a FREE implementation of the Border Gateway Protocol, Version 4.
It allows ordinary machines to be used as routers exchanging routes with
other systems speaking the BGP protocol.

WWW: https://www.openbgpd.org/
`
Please let me know if require more information. 

Thanks
Janak

**Comment by cjeker** [comment]
I did not consider to enable the pftable code for FreeBSD in -portable.
I changed the configure script to test for pfvar and pftable ioctl with this FreeBSD should pick up the real
pftable code instead of pftable-disabled.
This is in 88f41311a5dfe47751c8bf44fc07159cec98c228 and with that pftable code is compiled on FreeBSD and it seems to work as well.

**Comment by janakktrivedi** [comment]
Thank you very much!!!
I will try out.
