### ISSUE TITLE
Route refresh is ignored

### ISSUE THREAD

**Issue by zmousm** [openbgpd-portable/openbgpd-portable#46]
Apologies beforehand for posting this here rather than the OpenBSD bugs list.

I have observed that route refresh messages are discarded unexpectedly by OpenBGPD, at least in my tests with a neighbor which does not support RFC7313 (enhanced route refresh capability). `route refresh: AID IPv4 unicast not negotiated` is logged and apparently points to a regression introduced in [`rde.c` revision 1.548](https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.sbin/bgpd/rde.c#rev1.548). Also considering the description therein, the issue is indeed fixed with the following one-line change:

```diff
--- a/src/bgpd/rde.c	2022-10-03 18:20:06.000000000 +0300
+++ b/src/bgpd/rde.c	2023-01-12 19:59:10.540874769 +0200
@@ -1122,7 +1122,7 @@
 			    "route refresh: bad AID %d", rr.aid);
 			break;
 		}
-		if (peer->capa.mp[rr.aid]) {
+		if (peer->capa.mp[rr.aid] == 0) {
 			log_peer_warnx(&peer->conf,
 			    "route refresh: AID %s not negotiated",
 			    aid2str(rr.aid));
```

**Comment by cjeker** [comment]
Fixed in rev. 1.586 of rde.c, thanks for the report.
