### ISSUE TITLE
Using `local-as` assumes 4-octet AS specific extended community

### ISSUE THREAD

**Issue by zmousm** [openbgpd-portable/openbgpd-portable#47]
Apologies beforehand for posting this here rather than the OpenBSD bugs list.

I observed that using `local-as` in such a statement: `match ... set ext-community rt local-as:neighbor-as` assumes a 4-octet AS specific extended community type (per RFC5668), even if a 2-octet AS is actually used through global `AS` or neighbor/group `local-as` configuration.

The inadvertent effect is that upon an update reaching such a statement for a peer with a 4-octet `neighbor-as`, the action is silently discarded without anything being logged, after checking the _Local Administrator sub-field_ value does not "fit" (see `src/bgpd/rde_community.c` line 125 in `fc2c()`).

A workaround is to use the actual AS number for the particular field in the statement, either as a literal or perhaps with a macro.

Considering that the actual local AS number might be available somehow while parsing such a statement, `getcommunity()` and/or `parseextvalue()` should ideally check if `local-as`, when used for the _Global Administrator sub-field_ value, is a 2-octet or 4-octet AS number before setting the respective flag.

**Comment by cjeker** [comment]
In general people should use large-communities instead of ext-communities and communities.
Large communities work in all cases because the format is 4-byte by default.
For ext-communities the variable encoding of 2 vs 4 byte ASnum makes them a painful to handle in code.
I agree that `local-as` should be handled special when it comes to ext-community handling.

**Comment by zmousm** [comment]
I agree for large communities, however they are still not ubiquitous...
Do you think it would be feasible to check on the configured `local-as` upon parsing such statements? If not, maybe the behavior should be documented at least, so as to avoid silently surprises, such as the case I noted previously.

**Comment by cjeker** [comment]
There is a fix for ext-community encoding in -current.
It is probably not perfect but in the end only large-communities work in all cases.
