### ISSUE TITLE
Discrepancies in role config docs

### ISSUE THREAD

**Issue by pierky** [openbgpd-portable/openbgpd-portable#50]
Hello,

the docs at https://man.openbsd.org/bgpd.conf#role say that this is how rfc9234 roles can be configured:

```
role role
Set the local role for this eBGP session. The role can be one of none, provider, customer, rs, rs-client, or peer. If the role is set to none the announce policy will also be disabled.

announce policy (yes|no|enforce)
If set to yes, add the open policy role capability. If the role of the neighbor does not correspond to the expected role then the session will be closed. If enforce is set the session will only establish if the neighbor also announces the open policy capability. The default is no.
```

However, it seems that the config bgpd (7.7) expects is something like `announce policy $ROLENAME [enforce]`.

**Comment by cjeker** [comment]
The config was changed between 7.7 and -current.
The old config was indeed `announce policy $ROLENAME [enforce]` but with the addition of ASPA support
it made sense to move the role definition outside of the rfc9234 specific announce policy config option.
So -current and with that OpenBGPD 7.8 will use the new `role role` config option for both ASPA and rfc9234.

**Comment by pierky** [comment]
Oh I see, thanks for the update. I'll take the new syntax into account for future releases (>=7.8).
