### ISSUE TITLE
Invalid nexthop for GRE interfaces

### ISSUE THREAD

**Issue by janakktrivedi** [openbgpd-portable/openbgpd-portable#52]
I have OpenBGPD 7.6 ported in FreeBSD 13.1. It seems be stable and working fine, however I noticed OpenBGPD does not redistributes GRE interfaces by default until OpenBGPD service is restart. It marks the nexthop as "invalid" for all routes learn via GRE interface.

Here is some of the logs captured:
Mar 17 09:38:33 R0 bgpd[69221]: if_change: gre45: rdomain 0 DOWN, unknown media, active, 0 bps
Mar 17 09:38:57 R0 bgpd[69221]: if_change: gre46: rdomain 0 DOWN, unknown media, active, 0 bps

 

Interface      rdomain  Nexthop  Flags  Link state
**gre46          0        invalid         active
gre45          0        invalid         active
gre44          0        invalid         active
gre43          0        invalid         active**
gre42          0        ok       UP     active
gre41          0        ok       UP     active

Here GRE43 to GRE46 are UP and running and able to reach other endpoint of GRE, but BGPD can't see it. All the Physical and vlan interfaces had no issues observed with bgp. It is only GRE is impacted.
It seems like interfaces does not give proper media type and due to that BGPD marked it down.
https://github.com/openbgpd-portable/openbgpd-portable/blob/175c93b6e833fa1a23fbe15ee15a64927bcf2053/src/bgpd/kroute-freebsd.c

Anybody observed such behavior or could be bug. 

Any help would be much appreciated.

**Comment by cjeker** [comment]
On my FreeBSD testbox running 14.0-current it seems to work fine.
Here some commands from my system when I tested this:

```
# bgpctl show int
Interface      rdomain  Nexthop  Flags  Link state
lo0            0        ok       UP     active
re1            0        ok       UP     Ethernet, active, 1000 MBit/s
re0            0        invalid         Ethernet, no network
# ifconfig gre0 create
# bgpctl show int
Interface      rdomain  Nexthop  Flags  Link state
gre0           0        invalid         unknown
lo0            0        ok       UP     active
re1            0        ok       UP     Ethernet, active, 1000 MBit/s
re0            0        invalid         Ethernet, no network
# ifconfig gre0 inet 192.168.1.1 192.168.2.1
# bgpctl show int
Interface      rdomain  Nexthop  Flags  Link state
gre0           0        invalid         unknown
lo0            0        ok       UP     active
re1            0        ok       UP     Ethernet, active, 1000 MBit/s
re0            0        invalid         Ethernet, no network
# ifconfig gre0 tunnel 10.83.0.143 10.83.0.5
>> bgpd log: if_change: gre0: rdomain 0 UP, unknown media, active, 0 bps
# bgpctl show int
Interface      rdomain  Nexthop  Flags  Link state
gre0           0        ok       UP     active
lo0            0        ok       UP     active
re1            0        ok       UP     Ethernet, active, 1000 MBit/s
re0            0        invalid         Ethernet, no network
```

So it seems to work. The moment the interface has its tunnel endpoints set the FreeBSD kernel sends a `RTF_IFINFO` message which alters the state to `UP`.
Please provide exact commands on how to get into that state.
Either this was fixed in14.0-current but not backported or my way to configure the interface is missing the crucial step.
