### ISSUE TITLE
No debugging options in bgplgd

### ISSUE THREAD

**Issue by robert-scheck** [openbgpd-portable/openbgpd-portable#55]
I try to use `bgplgd` with the [FastCGI support in HAProxy](https://www.haproxy.com/de/blog/load-balancing-php-fpm-with-haproxy-and-fastcgi/), but I'm ending up with "HTTP 503" only. @job provided me a configuration snippet for the Apache webserver, which works fine there:

```
<Location "/bgplgd/">
    ProxyPass "unix:/var/run/bgplgd.sock|fcgi://localhost/"
    ProxyFCGISetEnvIf "reqenv('SCRIPT_NAME') =~ m|/bgplgd(/.*)|" PATH_INFO "$1"
</Location>
```

For HAProxy, I use:

```
frontend main
    bind *:80
    default_backend bgplgd

backend bgplgd
    use-fcgi-app socket
    server local /var/run/bgplgd.sock proto fcgi

fcgi-app socket
    log-stderr global
    docroot /var/empty
    path-info ^/bgplgd(/.*)$
```

Given HAProxy's FastCGI support works fine with PHP-FPM, and I can not see any hints or failures on HAProxy side, I wonder if there is any chance for debugging options in `bgplgd`? I'm also happy about hints…

**Comment by cjeker** [comment]
For debugging purposes I run bgplgd with -d to see all the arguments passed via fastcgi.
In most cases the problem has to do with `PATH_INFO`, `QUERY_STRING` and `REQUEST_METHOD` not being set the way the code expects.

**Comment by robert-scheck** [comment]
Bah, it seems like HAProxy 2.6.12-r0 as shipped by Alpine 3.17 has broken Unix socket handling in its fcgi backend: If I replace
```
    server local /var/run/bgplgd.sock proto fcgi
```
by
```
    server local 127.0.0.1:1234 proto fcgi
```
and run `socat TCP-LISTEN:2375,fork UNIX-CONNECT:/var/www/run/bgplgd.sock`, there is `bgplgd` output (similar to yours) for the very first time!

**Comment by robert-scheck** [comment]
> Bah, it seems like HAProxy 2.6.12-r0 as shipped by Alpine 3.17 has broken Unix socket handling in its fcgi backend: […]

I have to revert that partially, because running `ncat -k -l -U /var/run/bgplgd.sock | hexdump -C &` returns

```
00000000  01 01 00 01 00 08 00 00  00 01 01 00 00 00 00 00  |................|
00000010  01 04 00 01 01 7a 00 00  09 0e 48 54 54 50 5f 48  |.....z....HTTP_H|
00000020  4f 53 54 6c 6f 63 61 6c  68 6f 73 74 3a 35 30 30  |OSTlocalhost:500|
00000030  30 0f 0a 48 54 54 50 5f  55 53 45 52 5f 41 47 45  |0..HTTP_USER_AGE|
00000040  4e 54 63 75 72 6c 2f 38  2e 30 2e 31 0b 03 48 54  |NTcurl/8.0.1..HT|
00000050  54 50 5f 41 43 43 45 50  54 2a 2f 2a 11 07 47 41  |TP_ACCEPT*/*..GA|
00000060  54 45 57 41 59 5f 49 4e  54 45 52 46 41 43 45 43  |TEWAY_INTERFACEC|
00000070  47 49 2f 31 2e 31 0d 01  44 4f 43 55 4d 45 4e 54  |GI/1.1..DOCUMENT|
00000080  5f 52 4f 4f 54 2f 09 08  50 41 54 48 5f 49 4e 46  |_ROOT/..PATH_INF|
00000090  4f 2f 6d 65 74 72 69 63  73 0b 08 52 45 51 55 45  |O/metrics..REQUE|
000000a0  53 54 5f 55 52 49 2f 6d  65 74 72 69 63 73 0e 03  |ST_URI/metrics..|
000000b0  52 45 51 55 45 53 54 5f  4d 45 54 48 4f 44 47 45  |REQUEST_METHODGE|
000000c0  54 0b 0e 53 45 52 56 45  52 5f 4e 41 4d 45 6c 6f  |T..SERVER_NAMElo|
000000d0  63 61 6c 68 6f 73 74 3a  35 30 30 30 0b 04 53 45  |calhost:5000..SE|
000000e0  52 56 45 52 5f 50 4f 52  54 35 30 30 30 0f 08 53  |RVER_PORT5000..S|
000000f0  45 52 56 45 52 5f 50 52  4f 54 4f 43 4f 4c 48 54  |ERVER_PROTOCOLHT|
00000100  54 50 2f 31 2e 31 0b 09  52 45 4d 4f 54 45 5f 41  |TP/1.1..REMOTE_A|
00000110  44 44 52 31 32 37 2e 30  2e 30 2e 31 0b 05 52 45  |DDR127.0.0.1..RE|
00000120  4d 4f 54 45 5f 50 4f 52  54 34 32 37 39 36 0f 01  |MOTE_PORT42796..|
00000130  53 43 52 49 50 54 5f 46  49 4c 45 4e 41 4d 45 2f  |SCRIPT_FILENAME/|
00000140  0f 09 50 41 54 48 5f 54  52 41 4e 53 4c 41 54 45  |..PATH_TRANSLATE|
00000150  44 2f 2f 6d 65 74 72 69  63 73 0e 01 43 4f 4e 54  |D//metrics..CONT|
00000160  45 4e 54 5f 4c 45 4e 47  54 48 30 0f 16 53 45 52  |ENT_LENGTH0..SER|
00000170  56 45 52 5f 53 4f 46 54  57 41 52 45 48 41 50 72  |VER_SOFTWAREHAPr|
00000180  6f 78 79 20 32 2e 36 2e  31 32 2d 66 35 38 38 34  |oxy 2.6.12-f5884|
00000190  36 32 01 04 00 01 00 00  00 00 01 05 00 01 00 00  |62..............|
```
for a `curl` call using above HAProxy configuration. But `bgplgd` only responds properly when it's wrapped through `socat` first.

**Comment by cjeker** [comment]
Very strange, I know that bgplgd works with nginx, apache, and openbsd's httpd.
Now FastCGI has a few optimisations that we don't support (multiple calls per connection and session pools) but that should not matter here. I have never used HAProxy before so investigation will take some time.

**Comment by robert-scheck** [comment]
Hrm, after updating to Alpine 3.18, it seems to work this morning. I didn't track down yet, if I got tricked somewhere in the last days, but it works as expected. Let's close this for now – and sorry for the noise.
