### ISSUE TITLE
Please add configure options for WWW_USER and /var/www/run/bgplgd.sock

### ISSUE THREAD

**Issue by robert-scheck** [openbgpd-portable/openbgpd-portable#56]
As of writing, neither `WWW_USER` nor `/var/www/run/bgplgd.sock` can be overriden using options for `./configure`. To increase the portability, it could make sense to change this, because what the `www` user to OpenBSD is, is e.g. `www-data` to Debian. And socket `/var/www/run/bgplgd.sock` is also not on a path that Linux distributions usually prefer. If this is considerated, the man pages also would need placeholders then.

**Comment by cjeker** [comment]
Happy to do so, I knew that -portable may need something but was not sure what.
Do we also need to provide extra knobs for `BGPLGD_USER` and `bgpctlsock` (-S option default)?

**Comment by robert-scheck** [comment]
> Do we also need to provide extra knobs for `BGPLGD_USER` and `bgpctlsock` (-S option default)?

Ehm…aren't there already `--with-bgplgd-user=user` for `BGPLGD_USER` and `RUNSTATEDIR` (via `--runstatedir=/run/bgpd`) for `bgpctlsock`?

**Comment by cjeker** [comment]
I see, I looked in the wrong tree :)
So the idea is to add a `--with-www-user=user` (defaults to `www`) and a `--wwwrunstatedir=path` which defaults to `/var/www/run`. Does that make sense?

**Comment by cjeker** [comment]
Merged #57
