### ISSUE TITLE
show ip bgp not working 

### ISSUE THREAD

**Issue by vbolshakov** [openbgpd-portable/openbgpd-portable#6]
While configuring bgplg from openBSD 6.6 i found that "bgpctl show ip bgp" not show any routes.
BGP sessions established, "bgpctl show ip bgp in" show routes
My bgpd config:

AS X
listen on A.B.C.D
#fib-update no
#rde rib Loc-RIB no evaluate

socket "/var/www/run/bgpd.rsock" restricted

neighbor A.B.C.E {
 remote-as X
 descr "GW"
 export none
}

**Comment by cjeker** [comment]
You need to have at least one filter rule that allows the routes in, e.g.:
```
allow from A.B.C.D
```

**Comment by vbolshakov** [comment]
Thank you.
Just missed this part of bgpd.conf manual.
