### ISSUE TITLE
Unable to start bgpd with libmnl

### ISSUE THREAD

**Issue by ll-kang** [openbgpd-portable/openbgpd-portable#61]
on ubuntu-22.04 using openbgpd-8.1, I'm stuck with a problem. When I do bgctl show fib I get permission denied，I found that it automatically loads the kroute-disabled.c. Then I downloaded libmnl using apt-get install -y libmnl-dev, but bgpd cannot start.
The escription is as followswhen I do bgpd -d:
startup
PF_KEY not available, disabling ipsec
mnl_attr_validate for RTA_METRICS failed.
mnl_cb_run error
failed to load routing table 0
route decision engine ready
peer closed imsg connection
fatal in RDE: Lost connection to parent
session engine ready
rtr engine ready
peer closed imsg connection
peer closed imsg connection
fatal in RTR: Lost connection to parent
SE: Lost connection to parent
session engine exiting
terminating

I want to know which kroute file should I choose, kroute-linux.c or kroute.c or others，and what dependencies should I install like libmnl?

**Comment by Amoled** [comment]
Same problem on RHEL 8.5

**Comment by cjeker** [comment]
See 9abfa3f135f62515557c78cc182dcc3a683c125e which is hopefully a fix for this issue.
`RTA_METRICS` is an undocumented mess. Since we don't use it, just ignore the object.
Since my linux test systems don't return `RTA_METRICS` I never seen this issue.

**Comment by cjeker** [comment]
No feedback, consider this closed
