### ISSUE TITLE
FIB issues on Debian 12 (bookworm)

### ISSUE THREAD

**Issue by udf2457** [openbgpd-portable/openbgpd-portable#62]
As I understand it there is now FIB support in OpenBGPD portable ?

If so, then I'm having issues with Debian 12 (bookworm).

I am 7.7 as [distributed by Debian ](https://packages.debian.org/stable/net/openbgpd)

However I'm getting `permission denied` when doing `sho fi`:

```
$ doas /usr/sbin/bgpctl sho fi
flags: B = BGP, C = Connected, S = Static
       N = BGP Nexthop reachable via this route
       r = reject route, b = blackhole route

flags prio destination                      gateway                         
permission denied
```

and `ip route sho` doesn't show learnt routes.

**Comment by cjeker** [comment]
The Linux netlink support requires libmnl. So please make sure you have that library and -dev package installed.
I think the official Debian package does not include netlink support. At least there is no libmnl dependency registered.

**Comment by cjeker** [comment]
Btw. 7.7 is a very old release. You should probably use the backports repository since that one includes much newer OpenBGPD releases (8.1 right now).
I will release 8.2 soon and I hope that this can be used to adjust the debian package to pick up libmnl as dependency and then provide that in backports.

**Comment by udf2457** [comment]
Completely passed me by that it was 7.7.  Thanks for pointing it out.

It is a shame for such a new Debian release to ship with an ancient version of OpenBGPD in the standard repo !

**Comment by cjeker** [comment]
Packages in sid and trixie now link with libmnl. Did not see any backports yet but I hope those will show up soon.
Also this is on 8.1 and not the latest 8.2 release (so there is another chance that this gets fixed).
Anyway this is something debian package maintainers need to fix so I close this issue now.
