### ISSUE TITLE
syntax error kroute-freebsd.c

### ISSUE THREAD

**Issue by kebre001** [openbgpd-portable/openbgpd-portable#68]
There seems to be a syntax error in src/bgpd/kroute-freebsd.c:
https://github.com/openbgpd-portable/openbgpd-portable/blob/master/src/bgpd/kroute-freebsd.c#L2923

Seems to be part of commit:
https://github.com/openbgpd-portable/openbgpd-portable/commit/89bf06fb033980b4215f4f9090e59a5776e25812#diff-ca10a7b5850974c5e022839208f1ac43697252f9bfdd32edc7edb7c6150eb25eR2923

The error when compiling:
```
kroute-freebsd.c:2925:3: error: expected expression
                else
                ^
kroute-freebsd.c:2958:1: error: function definition is not allowed here
{
^
```

When I removed the "{" everything compiled as usual =)

**Comment by cjeker** [comment]
Yes, there was an extra '{' left. I fixed that.
