### ISSUE TITLE
FreeBSD port: session_setup_socket() fails at setsockopt(.., IP_TOS) step post freebsd commit de15626  

### ISSUE THREAD

**Issue by snallanc** [openbgpd-portable/openbgpd-portable#70]
Hello OpenBGPD Team,

At NetApp, we are using OpenBGPD 6.8p3 for leveraging BGP functionality in ONTAP based of FreeBSD.
After patching the FreeBSD commit de15626, I realised that BGP sessions don't come UP as they would normally:
- https://github.com/freebsd/freebsd-src/commit/de156263a598a0277b7bbc13ef8bdc6f4541b604

The above commit changes the way how the return value of ip_ctloutput() is further propagated to the caller for IP level socket options like IP_TOS in tcp_ctloutput_set() function within tcp_usrreq.c file:
/*
		 * When an IP-level socket option affects TCP, pass control
		 * down to stack tfb_tcp_ctloutput, otherwise return what
		 * IP level returned.
		 */
....
....
case IPPROTO_IP:
			switch (sopt->sopt_name) {
			case IP_TOS:
			case IP_TTL:
				/* Notify tcp stacks that care (e.g. RACK). */
				break;
			default:
				return (error);
			}
			break;

In the bgpd logs, I found that session_setup_socket() function in session.c was failing at setsockopt() step while trying to set IP_TOS option.
int
session_setup_socket(struct peer *p)
{
	int	ttl = p->conf.distance;
	int	pre = IPTOS_PREC_INTERNETCONTROL;
	int	nodelay = 1;
	int	bsize;

	switch (p->conf.remote_addr.aid) {
	case AID_INET:
		/* set precedence, see RFC 1771 appendix 5 */
		if (setsockopt(p->fd, IPPROTO_IP, IP_TOS, &pre, sizeof(pre)) ==
		    -1) {
			log_peer_warn(&p->conf,
			    "session_setup_socket setsockopt TOS");                        <<<<     Hitting this path
			return (-1);
		}
...
...

nsudarsh-vsim3% cat /BUILD | grep BSD
BSDVER: 14.0
nsudarsh-vsim3%

nsudarsh-vsim3% sudo cat /var/etc/bgpd.conf 
AS 65501
router-id 10.224.101.156
fib-update no
socket "/var/run/res.sock" restricted
holdtime 180

neighbor 10.224.101.161 {
         descr "1" 
         remote-as 65501
         local-address 10.224.101.157
         sysvsid 4294967295
         localpref 100
         vsid 0
}

nsudarsh-vsim3% grep -i bgp /var/log/messages.log.00000000000000000010
00000001.00006d27 00003677 Thu Nov 23 2023 23:06:40 -05:00 [daemon:info] 1 2023-11-23T23:06:40.179043-05:00 nsudarsh-vsim3 bgpd 8602 - - BGP Peers: local 10.224.101.157, neighbor 10.224.101.161 (1):
 state change None -> Idle, reason: None
00000001.00006d28 00003677 Thu Nov 23 2023 23:06:40 -05:00 [daemon:info] 1 2023-11-23T23:06:40.179539-05:00 nsudarsh-vsim3 bgpd 8602 - - BGP Peers: local 10.224.101.157, neighbor 10.224.101.161 (1):
 state change Idle -> Connect, reason: Start
00000001.00006d29 00003677 Thu Nov 23 2023 23:06:40 -05:00 [daemon:error] 1 2023-11-23T23:06:40.180223-05:00 nsudarsh-vsim3 bgpd 8602 - - BGP Peers: local 10.224.101.157, neighbor 10.224.101.161 (1)
: session_setup_socket setsockopt TOS: Protocol not available                       <<<<<<  setsockopt() fails here
00000001.00006d2a 00003677 Thu Nov 23 2023 23:06:40 -05:00 [daemon:info] 1 2023-11-23T23:06:40.180307-05:00 nsudarsh-vsim3 bgpd 8602 - - BGP Peers: local 10.224.101.157, neighbor 10.224.101.161 (1):
 state change Connect -> Active, reason: Connection open failed                   <<<<<< BGP connection fails

nsudarsh-vsim3% sudo bgpctl show neighbor
BGP neighbor is 10.224.101.161, remote AS 65501
 Description: 1
  BGP state = Active
  Last read Never, holdtime 240s, keepalive interval 80s
  Last write Never

  Message statistics:
                  Sent       Received  
  Opens                    0          0
  Notifications            0          0
  Updates                  0          0
  Keepalives               0          0
  Route Refresh            0          0
  Total                    0          0

  Update statistics:
                  Sent       Received  
  Prefixes                 0          0
  Updates                  0          0
  Withdraws                0          0
  End-of-Rib               0          0

nsudarsh-vsim3% 

I couldn't find any reference about this specific issue in the list of OpenBGPD-portable commits and issues.
Also, even in the latest openbgpd-portable-8.3 version, I see the same setsockopt() code in session_setup_socket() function. 
Could someone please confirm if this is still an issue?  If yes, please dup it to the existing issue and point me to that. If not, please clarify if this got addressed by one of FreeBSD or OpenBGPD communities and also point me to the fix.

Thanks,
Sudarshan

**Comment by cjeker** [comment]
This is a bug introduced into FreeBSD. Nothing we can really do. Please open an issue in their bug tracker.
They really need to stop breaking fundamental network APIs.

**Comment by snallanc** [comment]
Thanks @cjeker. Will file a FreeBSD bug to track this. Not sure if there are many FreeBSD userspace applications that set/get IP level socket options like IP_TOS but I agree in general with you.

**Comment by cjeker** [comment]
On Sun, Nov 26, 2023 at 08:34:07PM -0800, snallanc wrote:
> Thanks @cjeker. Will file a FreeBSD bug to track this. Not sure if there
> are many FreeBSD userspace applications that set/get IP level socket
> options like IP_TOS but I agree in general with you.
 
How about ssh and its IPQoS option? There are for sure other ones as well.

-- 
:wq Claudio
