### ISSUE TITLE
Unable to Provide ASPA Objects via RTR

### ISSUE THREAD

**Issue by MirrorTune** [openbgpd-portable/openbgpd-portable#71]
I attempted to provide the validation results of rpki-client via RTR (Version 2) to OpenBGPD, using two Ubuntu 22.04 machines (Ubuntu_A and Ubuntu_B) deployed in a virtual environment. While I was able to provide ROA objects, I could not provide ASPA objects.

【Environment】
Ubuntu_A (172.24.10.120): rpki-client 8.6 and Stayrtr v0.5.1 (compatible with RTRv2)
Ubuntu_B (172.24.10.179): OpenBGPD 8.3

I executed the rpki-client and generated a JSON file, which was then specified as a cache file to run Stayrtr, using the following command:

`stayrtr -protocol 2 -cache /usr/local/var/db/rpki-client/json &`

In the OpenBGPD config (bgpd.conf), I wrote the following. Currently, I am testing the provision of validation results via RTR, so I haven't written settings for include (include "/usr/local/var/db/rpki-client/openbgpd") or neighbors, which are generated by the rpki-client.

```
ASN="65001"
AS $ASN

router-id 172.24.10.179

prefix-set mynetworks {
    172.24.10.0/24
}

network prefix-set mynetworks set large-community $ASN:1:1

allow to ebgp
allow from ebgp

rtr 172.24.10.120 {
        descr Ubuntu_A
        port 8282
}

```

When checking the state of the RTR session with "bgpctl show rtr," the output seems to be fine.

```
bgpctl show rtr

RTR neighbor is 172.24.10.120, port 8282
 Description: Ubuntu_A
 Session ID: 42450 Serial #: 1
 Refresh: 3600, Retry: 600, Expire: 7200

  RTR RefreshTimer     due in 00:58:33
  RTR ExpireTimer      due in 01:58:33

```

When checking the state of each object with "bgpctl show sets," it is confirmed that ROA objects are being provided correctly via RTR, but the ASPA objects are listed as "Never," indicating they are not being provided.

```
bgpctl show sets
Type   Name                                 #IPv4   #IPv6 #ASnum Last Change
ROA    RPKI ROA                            293275   70582      -    00:09:41
ASPA   RPKI ASPA                                -       -      0       Never
PREFIX mynetworks                               1       0      -    00:14:12
```

The Stayrtr v0.5.1 I used is compatible with RTRv2 communication, and OpenBGPD has been compatible since version 7.8, as stated in the release notes.

["Add ASPA support for the RTR protocol based on draft-ietf-sidrops-8210bis-10"](https://marc.info/?l=openbsd-tech&m=167907442610114&w=2)

Why can't ASPA objects be provided via RTR?

**Comment by cjeker** [comment]
ASPA is currently in a state of flux. The RTR bits are based on a draft that is not compatible with the ASPA profile and verification drafts. Right now I can only suggest to not use ASPA until these issues are resolved at SIDROPS.
I fear that stayrtr is not correctly reading the data from rpki-client and so does not send any ASPA PDUs but that is me guessing.

**Comment by cjeker** [comment]
I can confirm that the problem is in `stayrtr` and OpenBGPD is working fine.
See https://github.com/bgp/stayrtr/pull/105 for a possible fix.

**Comment by MirrorTune** [comment]
Thank you for the quick fix.
By running Stayrtr on your modified source code, you can now serve ASPA objects to OpenBGPD via RTR.

```
bgpctl show sets
Type   Name                                 #IPv4   #IPv6 #ASnum Last Change
ROA    RPKI ROA                            240955   56649      -    00:08:52
ASPA   RPKI ASPA                                -       -     25    00:28:57
PREFIX mynetworks                               1       0      -    16:29:04
```

Thank you for fixing the bug.
