### ISSUE TITLE
OpenBGPD 8.4 does not work on FreeBSD or Rocky Linux on BuyVM

### ISSUE THREAD

**Issue by neelchauhan** [openbgpd-portable/openbgpd-portable#76]
I have a BuyVM VPS running OpenBGPD. When I try using 8.4 on both FreeBSD 14.0 (via Ports) and Rocky Linux 9.3 (via EPEL), I am unable to advertise IPv6 BGP. It is not routable on both systems.

If I use the 12-year-stale OpenBDPD 4.1 on FreeBSD via Ports, I can advertise IPv6 just fine and it is advertised.

My config is:

`AS 33535
router-id 198.98.54.21

listen on ::1
listen on 2605:6400:10:d::1
log updates
network 2602:XXX:2::/48
network 2602:XXX:3::/48

neighbor 2605:6400:ffff::2 {
        remote-as               53667
        descr                   "BuyVM BGP"
        announce IPv4           none
        announce IPv6           unicast
        tcp md5sig password     XXXXXXXX
        multihop                2
        local-address           2605:6400:X:X::1
}
`

This VPS is running an IPv6-only ASN, mainly as a private IPv6 tunnel (because HE.net is blocked on most streaming services).

**EDIT:** For reference, OpenBGPD 8.4 works on Vultr.

**Comment by cjeker** [comment]
That config can not work since OpenBGPD follows RFC8212 which requires filters explicitly allowing the prefix out.

So you need to have at least:
```
allow to ebgp prefix { 2602:XXX:2::/48 2602:XXX:3::/48 }
```

**Comment by neelchauhan** [comment]
Thank you so much 💕! This worked perfectly.

OpenBGPD 4.1 worked probably because it's old and BuyVM's BGP let that through.
