### ISSUE TITLE
"nexthop qualify via bgp" evaluates the nexthop only once

### ISSUE THREAD

**Issue by ssinyagin** [openbgpd-portable/openbgpd-portable#81]
I need to inject routes into an iBGP network, and the next-hop address is learned via iBGP.  I've set up openbgpd 8.5 with "nexthop qualify via bgp"  statement.

A configuration like 
```
network 10.66.67.0/28 set nexthop 172.22.22.8
```
does not have any effect on startup, as the route for `172.22.22.8` is not yet known via BGP. But by the time we receive the announcement for `172.22.22.8`, openbgpd does not try to re-evaluate its visibility, so the neighbour never receives an update for `10.66.67.0/28`.

If I inject the route via bgpctrl, the next-hop route is already learned, so it announces the update as expected. But if the next-hop is withdrawn and re-inserted from BGP because of some network changes in the upstream, the neighbour never receives an update.

As a workaround, I configured `nexthop qualify via default`, which makes the next-hop always resolvable, and the daemon works as expected, announcing the networks to its neighbours every time it's needed.

It's still desirable for the daemon to actually re-evaluate the next-hop feasibility when the RIB gets updated.

**Comment by cjeker** [comment]
This should be fixed with b928db175ec4f0cd46f788583e41aa5bb9e4c06a
Please test.

**Comment by cjeker** [comment]
Fixed in the 8.6 release
