### ISSUE TITLE
OpenBGPD: pfkey_remove should wait for the md5 bgp connection to terminate gracefully in FreeBSD

### ISSUE THREAD

**Issue by snallanc** [openbgpd-portable/openbgpd-portable#82]
While playing around with md5 bgp peers on OpenBGPD running on a FreeBSD box, I noticed something. OpenBGPD immediately purges the SA entries in SADB associated with an md5 bgp peer via pfkey_remove() called from merge_peers() when neighbor entry is removed from bgpd.conf file. While purging the SA entries immediately appears OK,  this could mess up the graceful termination of the md5 bgp connection by the Session Engine(SE) via session_stop() and session_notification() calls. 

Why?
Because, by the time, SE pushes the BGP notification message to FreeBSD kernel, the SA entries could have been purged. When kernel processes this notification in tcp_ipsec_outut(), it would not find the SA entries to compute the TCP MD5 Signature of the notification packet. It would just drop the packet incrementing the tcpstat counter as seen from the FreeBSD source code linked below.
Counter Increment: http://fxr.watson.org/fxr/source/netipsec/xform_tcp.c?v=FREEBSD-13-STABLE#L314
Counter definition: http://fxr.watson.org/fxr/source/netinet/tcp_var.h?v=FREEBSD-13-STABLE#L695

session_notification() logs a message stating notification is sent. However, the tcpdump packet trace doesn't capture the notification packet. Also the TCPSTAT counter tcps_sig_err_buildsig incremented during this time which all clearly indicated that the notification packet never made it to wire.

Peer create:
=========
bgpd.conf:
AS 65501
router-id 10.224.101.152
fib-update no
socket "/var/run/res.sock" restricted
holdtime 180

neighbor 10.224.101.149 {
         descr "545" 
         remote-as 65501
         local-address 10.224.101.153
         sysvsid 4294967295
         localpref 100
         tcp md5sig password XXXXX
}

setkey -D:
10.224.101.149 10.224.101.153
        tcp mode=any spi=156316450(0x09513322) reqid=0(0x00000000)
        A: tcp-md5  XXXXX
        seq=0x00000000 replay=0 flags=0x00000000 state=mature 
        created: Aug 13 06:33:17 2024   current: Aug 13 06:33:17 2024
        diff: 0(s)      hard: 0(s)      soft: 0(s)
        last: Aug 13 06:33:17 2024      hard: 0(s)      soft: 0(s)
        current: 208(bytes)     hard: 0(bytes)  soft: 0(bytes)
        allocated: 2    hard: 0 soft: 0
        sadb_seq=1 pid=19151 refcnt=1
10.224.101.153 10.224.101.149
        tcp mode=any spi=4096(0x00001000) reqid=0(0x00000000)
        A: tcp-md5  XXXXX
        seq=0x00000000 replay=0 flags=0x00000000 state=mature
        created: Aug 13 06:33:17 2024   current: Aug 13 06:33:17 2024
        diff: 0(s)      hard: 0(s)      soft: 0(s)
        last: Aug 13 06:33:17 2024      hard: 0(s)      soft: 0(s)
        current: 280(bytes)     hard: 0(bytes)  soft: 0(bytes)
        allocated: 3    hard: 0 soft: 0
        sadb_seq=0 pid=19151 refcnt=1

netstat -an:
tcp4       0      0 10.224.101.153.59185                          10.224.101.149.179                            ESTABLISHED -1 

Peer Delete:
=========
setkey -D:
No SAD entries.

bgpd.conf:
AS 65501
router-id 10.224.101.152
fib-update no
socket "/var/run/res.sock" restricted
holdtime 180

bgpd log:
/var/log/messages.log.00000000000000102449:0000002e.00004465 00001be4 Tue Aug 13 2024 06:33:48 -04:00 [daemon:error] 1 2024-08-13T06:33:48.675270-04:00 nsudarsh-vsim2 bgpd 8952 - - BGP Peers: local 
10.224.101.153, neighbor 10.224.101.149 (545): sending notification: Cease, peer unconfigured

netstat -s -p tcp | grep -v 0:
tcp:        
        11 times failed to make signature due to no SA                <<<<  tcps_sig_err_buildsig incremented

nsudarsh-vsim2% sudo tcpdump -r e0e.pcap -nnvvve -M XXXXX | grep -i notification 
reading from file e0e.pcap, link-type EN10MB (Ethernet)
nsudarsh-vsim2% 

I noticed that when the same peer was recreated, it took longer for the bgp connection to come UP until the peer at the other end timed out the old connection after exhausting retransmissions since the other end doesn't know that the local peer died. 

This doesn't happen with non-md5 bgp connection where I always a Notification packet on the wire upon peer deletion.  
I think this needs to be fixed to make sure md5 bgp connection also terminates gracefully to avoid any delays associated with retransmissions.

**Comment by cjeker** [comment]
Thanks for the clear write up. A fix for this has just been committed to OpenBSD.
The openbgpd-openbsd repo will have that fix by tomorrow morning (CEST).

**Comment by cjeker** [comment]
Fixed in the 8.6 release
