### ISSUE TITLE
How to use gcov to trace the whole project?

### ISSUE THREAD

**Issue by fouzhe** [openbgpd-portable/openbgpd-portable#86]
Hi, I want to use gcov to see the coverage information of the project through the following building commands:
```sh
YACC=byacc CFLAGS="-fprofile-arcs -ftest-coverage" CXXFLAGS="-fprofile-arcs -ftest-coverage" LDFLAGS="-fprofile-arcs -ftest-coverage" ./autogen.sh && \
    YACC=byacc CFLAGS="-fprofile-arcs -ftest-coverage" CXXFLAGS="-fprofile-arcs -ftest-coverage" LDFLAGS="-fprofile-arcs -ftest-coverage" ./configure --disable-shared --enable-static --prefix=$PWD/install --sysconfdir=/etc --with-privsep-user=root --with-bgplgd-user=root && \
    YACC=byacc CFLAGS="-fprofile-arcs -ftest-coverage" CXXFLAGS="-fprofile-arcs -ftest-coverage" LDFLAGS="-fprofile-arcs -ftest-coverage" make && make install
```
However, since the openbsd is the submodule, I found I cannot trace the coverage information of this submodule. Do you have any suggests? Thanks.

**Comment by cjeker** [comment]
`autogen.sh` copies all relevant files out of the openbgpd-openbsd repo. During compile no file is referenced there anymore.
I never looked a gcov but it is well possible it trips over the chroots in bgpd. At least with gprof that is normally the number one issue (with number 2 being the issue that bgpd forks and execs into multiple processes).

Please provide more information. Especially configure output and make V=1 output.

**Comment by fouzhe** [comment]
> `autogen.sh` copies all relevant files out of the openbgpd-openbsd repo. During compile no file is referenced there anymore. I never looked a gcov but it is well possible it trips over the chroots in bgpd. At least with gprof that is normally the number one issue (with number 2 being the issue that bgpd forks and execs into multiple processes).
> 
> Please provide more information. Especially configure output and make V=1 output.

So that the `openbsd ` directory is no more needed after `autogen.sh`?

**Comment by cjeker** [comment]
Yes, it is no longer needed after `autogen.sh` ran.
