### ISSUE TITLE
Nightly GitHub Action failure: symbol ‘GRACEFUL’ is used, but is not defined as a token and has no rules

### ISSUE THREAD

**Issue by robert-scheck** [openbgpd-portable/openbgpd-portable#89]
The nightly GitHub Action for the container image [fails](https://github.com/openbgpd-portable/openbgpd-container/actions/runs/12335506867/job/34427029585#step:8:1832) since today with:

> ```
> #35 74.83 /bin/sh ../../ylwrap parse.y y.tab.c parse.c y.tab.h `echo parse.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output parse.output -- bison -y  
> #35 74.94 /tmp/openbgpd-portable/src/bgpd/parse.y:1963.28-35: error: symbol ‘GRACEFUL’ is used, but is not defined as a token and has no rules; did you mean ‘GRACEFU’?
> #35 74.94  1963 | 		| ANNOUNCE GRACEFUL NOTIFICATION yesno {
> #35 74.94       |                            ^~~~~~~~
> #35 74.94       |                            GRACEFU
> #35 74.94 /tmp/openbgpd-portable/src/bgpd/parse.y:1963.37-48: error: symbol ‘NOTIFICATION’ is used, but is not defined as a token and has no rules; did you mean ‘NOTIFICATIONL’?
> #35 74.94  1963 | 		| ANNOUNCE GRACEFUL NOTIFICATION yesno {
> #35 74.95       |                                     ^~~~~~~~~~~~
> #35 74.95       |                                     NOTIFICATIONL
> #35 74.95 make[1]: *** [Makefile:1167: parse.c] Error 1
> #35 74.95 make[1]: Leaving directory '/tmp/openbgpd-portable/src/bgpd'
> #35 74.95 make: *** [Makefile:409: all-recursive] Error 1
> ```

**Comment by botovq** [comment]
On Sun, Dec 15, 2024 at 01:36:46AM -0800, Robert Scheck wrote:
> The nightly GitHub Action for the container image [fails](https://github.com/openbgpd-portable/openbgpd-container/actions/runs/12335506867/job/34427029585#step:8:1832) since today with:

Should be fixed in the next sync:

https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.sbin/bgpd/parse.y.diff?r1=1.473&r2=1.474

**Comment by cjeker** [comment]
Latest run worked so this is fixed
