### ISSUE TITLE
Consider to make /var/run/bgpd.sock more configurable

### ISSUE THREAD

**Issue by robert-scheck** [openbgpd-portable/openbgpd-portable#9]
As of writing `/var/run/bgpd.sock` seems to be quite hardcoded in

  * `src/bgpctl/bgpctl.8`
  * `src/bgpd/bgpd.conf.5`
  * `src/bgpd/bgpd.8`

Passing `--localstatedir=/foo` to `./configure` indeed allows to relocate to `/foo/run/bgpd.sock`, but it does not seem to allow reaching `/run/bgpd.sock` (as preferred by modern Linux distributions such as Fedora) or even `/run/openbgpd/bgpd.sock` to avoid conflicts between different services maybe consuming the same generic socket name (even more preferred by Fedora).

A new `./configure` parameter such as `--runstatedir` (supported by recent [autoconf](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) versions) or another name might help here: `--runstatedir` could default to `$(localstatedir)/run` for backward compatibility and downstreams needing another path would need to set `--runstatedir` themself accordingly.

**Comment by cjeker** [comment]
The path selection can be improved and I guess for the man pages a similar approach to rpki-client-portable is needed. I will make sure that the next 6.7p0 release has this fixed.

**Comment by cjeker** [comment]
There is no recent autoconf that has runstatedir support. Only hacked up version in various linux distros. This is going to be painful, guess I will have to add something around this to make it fly.

**Comment by robert-scheck** [comment]
Feel free to use a differently named parameter, this was just a suggestion.

**Comment by cjeker** [comment]
This should be solved in 42becc4c9ca77673d60665a476164261c931a2b2

**Comment by cjeker** [comment]
Commit 2dddb75901260b48e424c9c6778d3df8628eaaba adds placeholders for the man pages. With this everything should be solved.

**Comment by robert-scheck** [comment]
This of course only works if the release tarball is created with a recent version of `autoconf`, not sure whether this is given.

**Comment by cjeker** [comment]
My assumption is that systems that want runstate dir to be different from `$(localstatedir)/run` will have a patched `autoconf`.
So adding an extra knob seems unnecessary. We can add it if there is indeed a real need for it.
